spring:
    application:
        name: yorpat
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            javax.persistence.schema-generation.scripts.action: create
            javax.persistence.schema-generation.scripts.create-target: target/generated-schema.sql
            hibernate.hbm2ddl.delimiter: ;
